app001/config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :students do
    collection do
      get :search
    end
  end
end

app001/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app001/app/models/group.rb
class Group < ApplicationRecord
    has_many :students
end

app001/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  def self.search(params)
    result = Student.includes(:group)
    if params['ln'].present?
      result = result.where(ln: params['ln'])
    end
    if params['name'].present?
      result = result.where(groups: {name: params['name']})
    end
    result.all
  end
end

app001/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app001/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app001/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, :search, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    params['search'] ||= {}
    
    if params.has_key?('search')
      @students = Student.search(params['search'])
    else
      @students = []
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:ln, :fn, :sn, :group_id)
    end
end

app001/app/helpers/application_helper.rb
module ApplicationHelper
end

app001/app/helpers/groups_helper.rb
module GroupsHelper
end

app001/app/helpers/students_helper.rb
module StudentsHelper
end

app001/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app001/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app001/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app001/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app001/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app001/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Test Project</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="/students">students</a></li>
              <li><a href="/groups">groups</a></li>
            </ul>
            <% if !params['search'].nil?%>
              <%= form_tag search_students_path(), method: :get do %>
              <%= text_field_tag 'search[ln]', params['search']['ln'] %>
              <%= text_field_tag 'search[name]', params['search']['name'] %>
              <%= submit_tag 'Искать' %>
              <% end %> 
            <%else%>
              <%= form_tag search_students_path(), method: :get do %>
              <%= text_field_tag 'search[ln]' %>
              <%= text_field_tag 'search[name]' %>
              <%= submit_tag 'Искать' %>
              <% end %> 
            <% end %>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Link</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app001/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ln %>
    <%= form.text_field :ln %>
  </div>

  <div class="field">
    <%= form.label :fn %>
    <%= form.text_field :fn %>
  </div>

  <div class="field">
    <%= form.label :sn %>
    <%= form.text_field :sn %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app001/app/views/students/edit.html.erb
<h1>Редактирование студента</h1>

<%= render 'form', student: @student %>

<%= link_to 'Показать', @student %> |
<%= link_to 'Вернутсья назад', students_path %>

app001/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Студенты</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Фамилия</th>
      <th scope="col">Имя</th>
      <th scope="col">Отчество</th>
      <th scope="col">Группа</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.ln %></td>
        <td><%= student.fn %></td>
        <td><%= student.sn %></td>
        <td><%= student.group.name %></td>
        <td><%= link_to 'Просмотр', student %></td>
        <td><%= link_to 'Редактирование', edit_student_path(student) %></td>
        <td><%= link_to 'Убить!', student, method: :delete, data: { confirm: 'Серьезно?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить нового студента', new_student_path %>

app001/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Назад', students_path %>

app001/app/views/students/search.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Фамилия</th>
      <th scope="col">Имя</th>
      <th scope="col">Отчество</th>
      <th scope="col">Группа</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |s| %>
        <tr onclick="window.location='/students/<%= s.id %>'">
            <td><%= s.ln %></td>
            <td><%= s.fn %></td>
            <td><%= s.sn %></td>
            <td><%= s.group.name %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app001/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Фамилия:</strong>
  <%= @student.ln %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @student.fn %>
</p>

<p>
  <strong>Отчество:</strong>
  <%= @student.sn %>
</p>

<p>
  <strong>Группа:</strong>
  <%= @student.group.id %>
</p>

<%= link_to 'Редактировать', edit_student_path(@student) %> |
<%= link_to 'Вернуться назад', students_path %>